version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI...
      - pip install awscli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 992382580810.dkr.ecr.eu-west-1.amazonaws.com
      - REPOSITORY_URI=992382580810.dkr.ecr.eu-west-1.amazonaws.com/wp-techtest
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
